public bool ShowACTIVELYATWORK { get; set; }
public bool ShowACTIVELYATWORK_B { get; set; }
public bool ShowSPOUSEACTIVELYATWORK { get; set; }
public bool ShowSPOUSEACTIVELYATWORK_B { get; set; }
public bool ShowAIDS { get; set; }
public bool ShowHOSPDISABLED { get; set; }
public bool ShowCHRONICDISEASE { get; set; }
public bool ShowHBPDIAGNOSEDREADING { get; set; }
public bool ShowDRIVING { get; set; }
public bool ShowMEDPROCADVISED { get; set; }
public bool ShowHEIGHTWEIGHT { get; set; }
public bool ShowPHYSICIANS { get; set; }
public bool ShowHEALTHHISTORY { get; set; }
public bool ShowEXISTINGCOVERAGE { get; set; }
public bool ShowQUALIFYINGEVENT { get; set; }
public bool ShowCOMPREHENSIVEHEALTHBENF { get; set; }
public bool ShowCOMPREHENSIVEHEALTHBENFRESPONSE { get; set; }
public bool ShowTOBACCOUSE { get; set; }
public bool ShowSPOUSETOBACCOUSE { get; set; }
public bool ShowDEPENDENTTOBACCO { get; set; }
public bool ShowCHGRANDCHFTSTUDENT { get; set; }
public bool ShowCHGRANDCHACTIVEWK { get; set; }
public bool ShowREPLACEMENT { get; set; }
public bool ShowREPLACEMENTRESPONSE { get; set; }
public bool ShowAGENTREPLACEMENT { get; set; }
public bool ShowEXISTINGINSURANCE { get; set; }
public bool ShowEXISTINGINSURANCERESPONSE { get; set; }
public bool ShowAGENTEXISTING { get; set; }
public bool ShowILLUSTRATIONCERT1 { get; set; }
public bool ShowAGENTNAIC { get; set; }
